version: '3.7'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    restart: always
    command: start-dev
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin

    volumes:
    - ${WEBAPP_STORAGE_HOME}/data:/opt/keycloak/standalone/data